INSERT INTO Products(Name, Description, Category, Price)
VALUES("Kayak","A boat for one person","WaterSports",275.00)
INSERT INTO Products(Name, Description, Category, Price)
VALUES("Lifejacket","Protective and fashionable","WaterSports",48.95)
INSERT INTO Products(Name, Description, Category, Price)
VALUES("Soccer Ball","FIFA-approved size and weight","Soccer",19.50)
INSERT INTO Products(Name, Description, Category, Price)
VALUES("Corner Flags","Give your playing field a professional touch","Soccer",34.95)
INSERT INTO Products(Name, Description, Category, Price)
VALUES("Stadium","Flat-packed 35,000-seat stadium","Soccer",79500.00)
INSERT INTO Products(Name, Description, Category, Price)
VALUES("Thinking Cap","Improve your brain efficiency by 75%","Chess",16.00)
INSERT INTO Products(Name, Description, Category, Price)
VALUES("Unsteady Chair","Secretly give your opponent a disadvantage","Chess",29.95)
INSERT INTO Products(Name, Description, Category, Price)
VALUES("Human Chess Board","A fun game for the family","Chess",75.00)
INSERT INTO Products(Name, Description, Category, Price)
VALUES("Bling-Bling King","Gold-plated, diamond-studded King","Chess",1200.00)

SELECT * FROM PRODUCTS